# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: bash echo.sh

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: ssh deploy  
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
    # Private Key  私钥
        SSH_PRIVATE_KEY: ${{ secrets. }}
    # Remote host   远程主机
        REMOTE_HOST: "111.231.20.180"
    # Remote user  远程主机登录用户
        REMOTE_USER: "root"
    # Remote port  远程主机登录端口
    #   REMOTE_PORT: 22
    # optional, default is 22
    # Source directory  源文件 目录
        SOURCE:  "/home/runner/work/cicd-test/cicd-test"
    # optional, default is 
    # Target directory  目标目录
        TARGET: "/root/"
    # optional, default is /home/REMOTE_USER/
    # Arguments to pass to rsync
    #ARGS: # optional, default is -rltgoDzvO
